import pygame

QUIT = pygame.USEREVENT
ADD_EXP = pygame.USEREVENT + 1
ENEMY_TOUCH = pygame.USEREVENT + 2
START_BATTLE = pygame.USEREVENT + 3
GAME_OVER = pygame.USEREVENT + 4
TAKE_DAMAGE = pygame.USEREVENT + 5
TURN_END = pygame.USEREVENT + 6
ENEMY_DAMAGE = pygame.USEREVENT + 7
REGEN = pygame.USEREVENT + 8
